### ISSUE TITLE
Example for adding timestamp

### ISSUE THREAD

**Issue by mglaze** [rajatthareja/ReportBuilder#14]
Is it possible to provide an example of how to include execution time per scenario to the report?

**Comment by tk8817** [comment]
Hi @mglaze , this information is present within the report. We display time per step, per scenario, and per feature. In the HTML version this is displayed in mm:ss , in the JSON report it is displayed as milliseconds. 

If you would like to include some custom data in the report, we pick up anything that is put out to the console and display it within the scenario it was output during.

**Comment by mglaze** [comment]
@tk8817 Thanks for the response. my in html report the mm::ss are all showing 00:00
![image](https://cloud.githubusercontent.com/assets/1659393/13407433/6d537e40-def6-11e5-9adb-c44fd8b02d95.png)

Any info would be helpful.

Using Cucumber 1.2.1, is

**Comment by tk8817** [comment]
Hi @mglaze , apologies if you missed it but this is called out in our Readme that ReportBuilder is for Cucumber 2.0+ 

```
Usage
Note: Works with cucumber(>= 2.1.0) test results in JSON format.
```

There were re-writes between 1.3 & 2.0 of many core cucumber components. These changes broke many awesome ruby gems and due to inactive authors - a lot are still broken today. As such, ReportBuilder was born to fill in this gap and provide support for the Cucumber that exists today.

I do not believe we will offer support for legacy versions. Can I ask what is holding you back from making the jump to 2.0+ , I just made it myself 2 months ago after finding replacement libs for my formatting / reporting gaps.

**Comment by mglaze** [comment]
ah! Makes sense. Thanks for the follow-up.

**Comment by rajatthareja** [comment]
@mglaze Your contributions and suggestions are most welcome.

**Comment by tk8817** [comment]
@mglaze - lets close this issue if you are satisfied with the response. 
As Rajat said, we would love any suggestions / improvements, feel free to open as new issues.
